### PR TITLE
ADD: Contour plotting libraries

### PR DESCRIPTION
**Pull request by AdamTheisen**
Functionality for creating a contour by passing in a dictionary of objects and fields, or for contouring data if not in an object.  Also includes ability to overlay station data as well as wind barbs and for the creation of a meshgrid of wind barbs.

### CODE REVIEW

**Comment by zssherman** [comment]
@AdamTheisen Seems to be just PEP8 errors.

**Comment by zssherman** [comment]
@AdamTheisen Any doc PEP8 stuff. i'll do a separate pull request as I'll look at some of Ken's new code etc to get everything up to the same style etc.

**Comment by AdamTheisen** [comment]
Thanks @zssherman I got all the PEP8 stuff worked out on my side and pushed again.

**Comment by AdamTheisen** [comment]
@zssherman  if you approve, I'll do the merge.  I don't want to do it one-sided here

**Comment by zssherman** [comment]
@AdamTheisen Looks good to me.

**Pull request merged**
