### PR TITLE
Geographic plot

### PR DESCRIPTION
**Pull request by kenkehoe**
Adding geographic plot for issue #45 .

### CODE REVIEW

**Comment by AdamTheisen** [comment]
Ken it looks like some pep8 items are causing it to fail:

./act/plotting/plot.py:43:1: E302 expected 2 blank lines, found 1
./act/plotting/plot.py:1058:40: E226 missing whitespace around arithmetic operator
./act/plotting/plot.py:1059:44: E226 missing whitespace around arithmetic operator
./act/plotting/plot.py:1607:5: E303 too many blank lines (2)
./act/plotting/plot.py:1705:40: E226 missing whitespace around arithmetic operator
./act/plotting/plot.py:1706:40: E226 missing whitespace around arithmetic operator
./act/plotting/plot.py:1708:44: E226 missing whitespace around arithmetic operator
./act/plotting/plot.py:1709:44: E226 missing whitespace around arithmetic operator
./act/plotting/plot.py:1710:44: E226 missing whitespace around arithmetic operator
./act/plotting/plot.py:1711:44: E226 missing whitespace around arithmetic operator
./act/plotting/plot.py:1715:38: W291 trailing whitespace
./act/tests/test_plotting.py:15:40: E241 multiple spaces after ','

**Comment by kenkehoe** [comment]
OK I've made some updates. Interesting because many of those errors did not report using flake8.

**Comment by AdamTheisen** [comment]
@rcjackson this looks good to me but will defer to you on the final merge.

**Comment by kenkehoe** [comment]
Do we have a decision on merging this pull request?

**Comment by scollis** [comment]
@rcjackson Is in Boulder at the moment and might be out of contact..

**Comment by AdamTheisen** [comment]
I'll go ahead and merge it since no checks are failing.

**Comment by rcjackson** [comment]
Weird, Outlook didn't even show me the email until today. The only thing that seems to be missing are the baseline plots for the unit tests. There should be a couple of extra .png files that represent the baseline for comparing the plot that the test puts out versus what it should look like.

**Comment by kenkehoe** [comment]
OK I'll look into adding them.

**Comment by kenkehoe** [comment]
Not sure but I don't think it works for me. Maybe someone else needs to make the plots to compare?

**Comment by rcjackson** [comment]
Did you get a specific error message or did it simply not generate any more plots in the baseline directory of tests?


Bobby

________________________________

**Comment by kenkehoe** [comment]
OK I was missing a library so it didn't run. I can get it to make plots now, but the plot is not what I expect. When I run the test function manually I get this plot 
test
 but the plot made by the py.test is this one 
test_time_height_scatter
Looks like some defaults for plotting are different between my environment and the py.test?

**Comment by rcjackson** [comment]
Ken:

I wonder if your py.test is running from another environment and pulling settings from there. Have you tried ensuring that pytest is installed in your current environment and not base?


Bobby

________________________________

**Comment by AdamTheisen** [comment]
The DMF systems are a little environment may cause issues.  I'll try testing once I finish up some MPL correction testing

**Pull request merged**
