### PR TITLE
Dl winds

### PR DESCRIPTION
**Pull request by kenkehoe**
Add function to convert Doppler Lidar PPI scans to winds.

### CODE REVIEW

**Comment by kenkehoe** [comment]
I guess I need to add a test before merging. I'll do that now.

**Comment by AdamTheisen** [comment]
@kenkehoe do we need all those DL files or would just 1 suffice for testing?

**Comment by AdamTheisen** [comment]
@zssherman @rcjackson I'm seeing a new error with the testing.  Can you take a look whenever you get a chance

**Comment by kenkehoe** [comment]
OK I'll look into reducing data files.

**Comment by zssherman** [comment]
@AdamTheisen Hmm, i wonder if a updated dependency is having a conflict with setuptools. I'll look into it.

**Comment by AdamTheisen** [comment]
Adding in example plot of the winds produced for documentation.

image

**Comment by AdamTheisen** [comment]
Discussing with Ken on how best to give credit to the author of the source code this was adapted from.

**Comment by rcjackson** [comment]
If they did not make the pull request I would give them credit in the docstring for the function. In addition, cite any relevant papers in the docstring.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by scollis** [comment]
Ditto @rcjackson Are they on GitHub? Best way to give someone credit is to accept a PR from them thus building traceability. You could have them make the PR with the acknowledgement...

**Comment by AdamTheisen** [comment]
Nope, not on github. base code was adapted to python by Ken but just want to make sure the author of the code this came from was appropriately cited.

**Comment by kenkehoe** [comment]
I think we need a way to list the Reference paper like PyART but also want to credit the original code Author (The DL Mentor Rob Newsom) since he did most of the programming work in IDL and I just transferred it to Python.

**Comment by AdamTheisen** [comment]
As a final note, there is not a type in numpydoc for Authors.  Going forward, we will reference the appropriate papers and add a note in function description if warranted beyond the paper reference.

**Pull request merged**
