### PR TITLE
ADD: Plotting of spatial datasets

### PR DESCRIPTION
**Pull request by rcjackson**
I have added support for plotting spatial datasets such as satellite data. This will basically support anything on a regular multidimensional grid, and even has the ability to pass in keywords into xarray to slice the dataset into the cross section you want before plotting.

I've also reorganized the plotting code to put each Display class in a separate file for easier readability. This does not affect any syntax.

### CODE REVIEW

**Comment by AdamTheisen** [comment]
It looks like your test_plotting.py might not have the latest updates.  

    __import__(modname)
E     File "/home/travis/build/ANL-DIGR/ACT/act/tests/test_plotting.py", line 11
E       from act.plotting import SkewTDisplay, XSectionDisplay,
E                               ^
E   SyntaxError: trailing comma not allowed without surrounding parentheses

The file I have has these parentheses in there

from act.plotting import (TimeSeriesDisplay, WindRoseDisplay,
                          SkewTDisplay, GeographicPlotDisplay)

**Comment by rcjackson** [comment]
I did have some conflicts and forgot to take out that comma when I was placing in the newest changes. Also, for now I'm not doing an image comparison for the test_time_height_scatter() since we are having issues with the baseline plot being generated incorrectly. It will run the test simply to see if it completes.

**Comment by AdamTheisen** [comment]
@rcjackson Looks like test_xsection_plot_map is failing now.  I'm trying to sort out the error messages, but looks like there are no files to open.  It's also looking like there's an issue with the sonde plotting in that the lat/lon passed into day_night_background are not numbers.  Is the day/night background needed for that one.  We could set to false to get around for now.

**Comment by AdamTheisen** [comment]
@rcjackson Thanks for requesting me as a reviewer on this, it has been helpful to go through the process.   Looks like just some PEP8 issues

./act/plotting/plot.py:23:5: F811 redefinition of unused 'ccrs' from line 13
./act/plotting/plot.py:291:20: W292 no newline at end of file
./act/tests/sample_files.py:38:1: W391 blank line at end of file
./act/tests/test_plotting.py:181:1: E302 expected 2 blank lines, found 1
./act/tests/test_plotting.py:193:1: E302 expected 2 blank lines, found 1

**Comment by AdamTheisen** [comment]
@rcjackson I tried pulling your branch to make these fixes, but it looks like they were resolved there already.  Is this just a matter of pushing the commits or am I missing something?

**Comment by rcjackson** [comment]
On my end they were not resolved. I went ahead and pushed the commit. All should be good to go now.

________________________________

**Comment by rcjackson** [comment]
All issues have been resolved. We can go ahead and merge.

**Pull request merged**
