### PR TITLE
ADD: New functions for correcting wind direction and speed for ship m…

### PR DESCRIPTION
**Pull request by AdamTheisen**
Functions for calculating course and speed over ground and for correcting wind data for ship motion.  Calculations have been tested over a months worth of MAR NAV and AOSMET data and compared with the MAR SONDE wind direction and speed data.

ship_corrections

### CODE REVIEW

**Comment by rcjackson** [comment]
I would write a unit test for this entry since it's a new feature, but otherwise everything else looks good.

**Comment by zssherman** [comment]
@AdamTheisen I approved, but I agree with Bobby, just unit tests, but everything else looks good.

**Comment by AdamTheisen** [comment]
Adding in 2 tests for course over ground calc and wind corrections.  Also adding in an example and fixed some documentation issues I came across while adding in the ship calcs to the autodocs.

**Comment by AdamTheisen** [comment]
Sorry, my flake8 did not catch those pep8 issues.

**Pull request merged**
