### PR TITLE
DOC: Adding a document on how to create and use conda environments. Added need environment yml file.

### PR DESCRIPTION
**Pull request by zssherman**

### CODE REVIEW

**Comment by rcjackson** [comment]
This is a nice idea. I would also like to see a link to this in the ACT github pages. If you need help with that, we can get together on Monday to make that happen.

**Comment by zssherman** [comment]
@rcjackson. I should be able to do it. If I can't we can meet as you mentioned, not sure if pelican style pages is much different.

**Comment by zssherman** [comment]
@rcjackson Did you want a link to the document on github or do you want the conda environment rst file embedded in the gh-pages ?

**Comment by rcjackson** [comment]
I would like to have a link to it in the gh-pages so that when someone clicks in the website they can get to it from there.


Bobby

________________________________

**Comment by rcjackson** [comment]
Basically, an extra section on the docs that you can click on the left hand panel and get to it.

**Comment by zssherman** [comment]
@rcjackson I forgot in the doc, there is a link to an environment.yml file for creating environments from that.  Want me to add an environment.yml file to the github repo?

**Comment by rcjackson** [comment]
Yes, that would be great.

________________________________

**Pull request merged**
