### PR TITLE
ENH: Updating code to work off a merged object

### PR DESCRIPTION
**Pull request by AdamTheisen**
Merging objects causing some issues with the attributes. Created some catches to help this

### CODE REVIEW

**Comment by rcjackson** [comment]
The flake8 checker failed. Since we want to have neat code that conforms to PEP8 standards, the following stylistic modifications to the code need to be done:
./act/plotting/plot.py:88:27: F821 undefined name 'arm'
./act/plotting/plot.py:121:16: E121 continuation line under-indented for hanging indent
./act/plotting/plot.py:146:32: E231 missing whitespace after ','
./act/plotting/plot.py:147:1: W293 blank line contains whitespace
./act/plotting/plot.py:323:56: W291 trailing whitespace
./act/plotting/plot.py:324:17: E128 continuation line under-indented for visual indent
./act/utils/datetime_utils.py:30:1: E302 expected 2 blank lines, found 1
./act/utils/datetime_utils.py:36:27: W291 trailing whitespace
./act/utils/datetime_utils.py:45:11: E222 multiple spaces after operator

**Comment by scollis** [comment]
Awesome. Adam, commuting changes to the same branch and then pushing to that branch on you fork (origin) will update the pull request 

-sent from a mobile device-

**Comment by AdamTheisen** [comment]
Interesting, I didn't touch some of these areas.  I'll go in and update

**Comment by rcjackson** [comment]
Just one more line to correct in plot.py:
./act/plotting/plot.py:324:33: E128 continuation line under-indented for visual indent

**Comment by rcjackson** [comment]
CI is now passing, merging.

**Pull request merged**
