### PR TITLE
CSV Reader

### PR DESCRIPTION
**Pull request by AdamTheisen**
Initial development of a CSV reader based on CSV files generated from ARM data discovery.  More work will be needed as we encounter different formats.  

Some slight updates to the plotting routine had to be made to work with the limited metadata that comes with csv files.

### CODE REVIEW

**Comment by AdamTheisen** [comment]
Looks like some of the tests failed.  I'll look into this a bit today

**Comment by AdamTheisen** [comment]
@rcjackson It seems like the last updates to have a dictionary pair in plotting are causing issues with the tests that are set up.  Is that what I'm seeing?  My previous scripts I had set up are no longer working after pulling the latest updates either which leads me to this.  I also had a couple errors come up that i had to modify the code to get around one with the warning and the other with how act_datastream was being set.

-                warnings.warn(UserWarning, ("Could not discern datastream" +
+                warnings.warn(("Could not discern datastream" +
                                             "name and dict or tuple were " +
                                             "not provided. Using default" +
-                                            "name of act_datastream!"))
-                self._arm = {'act_datastream', arm_obj}
+                                            "name of act_datastream!"),
+                                            UserWarning)
+                self._arm = {'act_datastream': arm_obj}

**Comment by rcjackson** [comment]
It looks like you have an older plot.py that you may have been working from and merged in. I see that the code in there doesn't account for the dictionary interface.

**Comment by rcjackson** [comment]
https://github.com/ANL-DIGR/ACT/pull/22/commits/45ca5029ae1e55cb5a0d55f47c376560fb2593c2

**Comment by AdamTheisen** [comment]
Thanks @rcjackson  i just saw that when I tried to sync up my fork with the main repo before that not all the changes came through it looks like.  I'll see what I can do

**Pull request closed without merging**
