### PR TITLE
Updates to QC Documentation and CBH Calc

### PR DESCRIPTION
**Pull request by AdamTheisen**
This would potentially overwrite Ken's although some modification may be needed after the fact

### CODE REVIEW

**Comment by AdamTheisen** [comment]
@kenkehoe Check this out and see.  I was able to get a lot more documentation to show up for QC functions and classes

**Comment by rcjackson** [comment]
You placed your changes from your other pull request on the sobel filter into here on accident @AdamTheisen. I think it would be easiest to just have them both in this PR, closing the other one.

**Comment by AdamTheisen** [comment]
I just saw that...  Will close out the other one and add the test here.  Likely will be later tonight or tomorrow.

**Comment by kenkehoe** [comment]
OK removing the /Users/kehoe/dev/dq/lib/python/ACT/docs/source/API/generated/ directory as Bobby suggested seems to have fixed my biggest issue. I suggest you make you merge and I will go back and fix any issues from my merge request.

**Comment by AdamTheisen** [comment]
Will wait for @rcjackson  to approve now that the cbh test is in before merging

**Comment by AdamTheisen** [comment]
Just wanted to add one last example for ceil data into the code

**Pull request merged**
