### PR TITLE
QC bar plot

### PR DESCRIPTION
**Pull request by kenkehoe**
Adding option to overplot data failing QC and use the flag_assessment to distinguish overplot color. Second addition is ability to make QC bar plot. Also fixed issue using wrong numpy masked array function for limiting range with plot. This is related to Issues #109  and #82 .

### CODE REVIEW

**Comment by kenkehoe** [comment]
Picture is easier to understand than words.

Figure_1

**Comment by AdamTheisen** [comment]
Looks like some pep8 issues

./act/tests/test_plotting.py:290:1: E302 expected 2 blank lines, found 1
./act/tests/test_plotting.py:295:58: E231 missing whitespace after ','
./act/tests/test_plotting.py:297:48: E231 missing whitespace after ':'
./act/tests/test_plotting.py:302:1: W293 blank line contains whitespace

**Comment by AdamTheisen** [comment]
This looks good and will be useful.  @rcjackson for a second opinion to see if the changes mesh well in the TimeSeriesDisplay code this was added to.

**Comment by rcjackson** [comment]
Looks good to me!

**Pull request merged**
