### PR TITLE
Colorblind Colormaps

### PR DESCRIPTION
**Pull request by ajsockol**
Registered the HomeyerRainbow colorblind friendly colormap so it can be accessed with "act_HomeyerRainbow". Additional customizable colormaps can be added to the act_cmap.py file as needed.

### CODE REVIEW

**Comment by zssherman** [comment]
Hi @ajsockol, I would just change:
```
from _act_cmap import datad, yuv_rainbow_24
```
to:
```
from ._act_cmap import datad, yuv_rainbow24
```

**Comment by zssherman** [comment]
@ajsockol The rest seems to just be some minor PEP8 stuff:

./act/plotting/act_cmap.py:20:1: E302 expected 2 blank lines, found 1
./act/plotting/act_cmap.py:70:1: E305 expected 2 blank lines after class or function definition, found 1
./act/plotting/act_cmap.py:95:52: W292 no newline at end of file
./act/plotting/_act_cmap.py:10:28: E226 missing whitespace around arithmetic operator
./act/plotting/_act_cmap.py:10:39: E226 missing whitespace around arithmetic operator
./act/plotting/_act_cmap.py:11:30: E226 missing whitespace around arithmetic operator
./act/plotting/_act_cmap.py:11:42: E226 missing whitespace around arithmetic operator
./act/plotting/_act_cmap.py:13:50: E226 missing whitespace around arithmetic operator
./act/plotting/_act_cmap.py:13:52: E226 missing whitespace around arithmetic operator
./act/plotting/_act_cmap.py:14:54: E226 missing whitespace around arithmetic operator
./act/plotting/_act_cmap.py:14:56: E226 missing whitespace around arithmetic operator
./act/plotting/_act_cmap.py:15:13: E226 missing whitespace around arithmetic operator
./act/plotting/_act_cmap.py:16:13: E226 missing whitespace around arithmetic operator
./act/plotting/_act_cmap.py:25:23: E226 missing whitespace around arithmetic operator
./act/plotting/_act_cmap.py:25:31: E226 missing whitespace around arithmetic operator
./act/plotting/_act_cmap.py:26:25: E226 missing whitespace around arithmetic operator
./act/plotting/_act_cmap.py:26:33: E226 missing whitespace around arithmetic operator
./act/plotting/_act_cmap.py:27:24: E226 missing whitespace around arithmetic operator
./act/plotting/_act_cmap.py:27:32: E226 missing whitespace around arithmetic operator
./act/plotting/_act_cmap.py:45:1: E303 too many blank lines (3)
./act/plotting/_act_cmap.py:48:57: E231 missing whitespace after ':'
./act/plotting/_act_cmap.py:48:71: W292 no newline at end of file

**Comment by ajsockol** [comment]
Looks like more PEP8 stuff. I'll make a few more changes; hopefully it will work.

**Comment by zssherman** [comment]
Thanks @ajsockol , @AdamTheisen merging.

**Pull request merged**
