### PR TITLE
Updated function to return QC variable names to use re instead of mat…

### PR DESCRIPTION
**Pull request by kenkehoe**
…ching everything exactly.

### CODE REVIEW

**Comment by AdamTheisen** [comment]
@kenkehoe Looks like the test_clean is throwing an error

       assert 'flag_masks' in ceil_ds['qc_first_cbh'].attrs.keys()
E       AssertionError: assert 'flag_masks' in odict_keys(['long_name', 'units', 'flag_method', 'description', 'standard_name'])
E        +  where odict_keys(['long_name', 'units', 'flag_method', 'description', 'standard_name']) = <built-in method keys of collections.OrderedDict object at 0x7ff4f72158c8>()
E        +    where <built-in method keys of collections.OrderedDict object at 0x7ff4f72158c8> = OrderedDict([('long_name', 'Quality check results on field: Lowest cloud base height detected'), ('units', 'unitless')... 'bit'), ('description', 'See global attributes for individual bit descriptions.'), ('standard_name', 'quality_flag')]).keys
E        +      where OrderedDict([('long_name', 'Quality check results on field: Lowest cloud base height detected'), ('units', 'unitless')... 'bit'), ('description', 'See global attributes for individual bit descriptions.'), ('standard_name', 'quality_flag')]) = <xarray.DataArray 'qc_first_cbh' (time: 5401)>\ndask.array<shape=(5401,), dtype=int32, chunksize=(5401,)>\nCoordinates:\n...hod:    bit\n    description:    See global attributes for individual bit descriptions.\n    standard_name:  quality_flag.attrs
act/tests/test_clean.py:24: AssertionError

**Comment by kenkehoe** [comment]
As soon as I committed I thought of my error. I've fixed it. 

How can I run all the tests locally before pushing?

**Comment by zssherman** [comment]
@kenkehoe You can do:
pytest -v
or:
pytest -v -pyargs act
pyargs if it's outside of the act directory

**Comment by kenkehoe** [comment]
Hold off one sec. I want to fix an issue with plotting and warnings that is not working as I expected.

**Comment by kenkehoe** [comment]
OK I have the initial issue resolved and I fixed a bunch of warnings. Ready to merge.

**Pull request merged**
