### PR TITLE
Adding QC stuff

### PR DESCRIPTION
**Pull request by kenkehoe**
As a 4th of July present for everyone, here is the updated code to use QC variables. This will move us closer to resolving #75 . This has methods to ensure QC variables are correct, add tests, remove tests, set test, unset tests and retrieve the data with the test applied in either masked array or set to NaN. Currently there are no actual tests in this commit. That will come next.

### CODE REVIEW

**Comment by kenkehoe** [comment]
The failures are not part of the new code I'm submitting. Looks to be failing tests from older plotting codes? Can we still merge this since my additions are not failing tests?

**Comment by AdamTheisen** [comment]
@rcjackson @zssherman can you check out the errors being produced?  Is this a case of old code being in the pull request or something else?

**Comment by zssherman** [comment]
No problem, I can take a look.

**Comment by AdamTheisen** [comment]
Note, I am getting different errors on my local copy for some reason

`test_retrieve_stability.py:10: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../retrievals/stability_indices.py:105: in calculate_stability_indicies
    p_sorted, t_sorted, td_sorted)
/anaconda3/lib/python3.7/site-packages/metpy/xarray.py:436: in wrapper
    return func(*args, **kwargs)
/anaconda3/lib/python3.7/site-packages/metpy/units.py:305: in wrapper
    return func(*args, **kwargs)
/anaconda3/lib/python3.7/site-packages/metpy/calc/thermo.py:1696: in surface_based_cape_cin
    p, t, td, profile = parcel_profile_with_lcl(pressure, temperature, dewpoint)
/anaconda3/lib/python3.7/site-packages/metpy/xarray.py:436: in wrapper
    return func(*args, **kwargs)
/anaconda3/lib/python3.7/site-packages/metpy/units.py:305: in wrapper
    return func(*args, **kwargs)
/anaconda3/lib/python3.7/site-packages/metpy/calc/thermo.py:556: in parcel_profile_with_lcl
    new_temp = _insert_lcl_level(pressure, temperature, p_lcl)
/anaconda3/lib/python3.7/site-packages/metpy/calc/thermo.py:594: in _insert_lcl_level
    interp_temp = interpolate_1d(lcl_pressure, pressure, temperature)
/anaconda3/lib/python3.7/site-packages/metpy/xarray.py:436: in wrapper
    return func(*args, **kwargs)
/anaconda3/lib/python3.7/site-packages/pint/registry_helpers.py:194: in wrapper
    result = func(*new_values, **kw)
/anaconda3/lib/python3.7/site-packages/metpy/interpolate/one_dimension.py:119: in interpolate_1d
    variables = [arr[sorter] for arr in args]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

.0 = <tuple_iterator object at 0x1c22c69ac8>

>   variables = [arr[sorter] for arr in args]
E   TypeError: tuple indices must be integers or slices, not tuple`

**Comment by zssherman** [comment]
I'm rerunning the test, not sure why metpy isn't being found, despite it being in the environment.yml files. The did a recent release about an hour ago so maybe conda-forge was trying to install something that was in the process of being uploaded. Why the units attr isn't now being found, I'm looking into that now.

**Comment by AdamTheisen** [comment]
@kenkehoe Looks like a lot of pep8 issues now.

++flake8 --max-line-length=115 --ignore=F401,E402,W504,W605
./act/io/clean.py:287:53: E128 continuation line under-indented for visual indent
./act/io/clean.py:295:55: E128 continuation line under-indented for visual indent
./act/io/clean.py:297:54: E128 continuation line under-indented for visual indent
./act/io/clean.py:300:55: E128 continuation line under-indented for visual indent
./act/io/clean.py:302:54: E128 continuation line under-indented for visual indent
./act/io/clean.py:305:56: E128 continuation line under-indented for visual indent
./act/io/clean.py:307:50: E128 continuation line under-indented for visual indent
./act/qc/qcfilter.py:88:21: E126 continuation line over-indented for hanging indent
./act/qc/qcfilter.py:110:29: E126 continuation line over-indented for hanging indent
./act/qc/qcfilter.py:214:21: E126 continuation line over-indented for hanging indent
./act/qc/qcfilter.py:369:21: E126 continuation line over-indented for hanging indent
./act/qc/qcfilter.py:376:21: E126 continuation line over-indented for hanging indent
./act/qc/qcfilter.py:633:17: E126 continuation line over-indented for hanging indent
./act/qc/qcfilter.py:681:21: E126 continuation line over-indented for hanging indent
./act/qc/qcfilter.py:709:17: E126 continuation line over-indented for hanging indent
./act/qc/qcfilter.py:718:17: E126 continuation line over-indented for hanging indent
./act/qc/qcfilter.py:729:17: E126 continuation line over-indented for hanging indent
./act/qc/qcfilter.py:740:17: E126 continuation line over-indented for hanging indent
./act/qc/qcfilter.py:751:17: E126 continuation line over-indented for hanging indent
./act/qc/qcfilter.py:762:21: E126 continuation line over-indented for hanging indent
./act/qc/qcfilter.py:773:21: E126 continuation line over-indented for hanging indent
./act/qc/qcfilter.py:785:21: E126 continuation line over-indented for hanging indent
./act/qc/qcfilter.py:798:21: E126 continuation line over-indented for hanging indent
./act/qc/qctests.py:45:33: E126 continuation line over-indented for hanging indent
./act/qc/qctests.py:111:33: E126 continuation line over-indented for hanging indent
./act/qc/qctests.py:182:33: E126 continuation line over-indented for hanging indent
./act/qc/qctests.py:254:33: E126 continuation line over-indented for hanging indent
./act/qc/qctests.py:327:33: E126 continuation line over-indented for hanging indent
./act/qc/qctests.py:397:33: E126 continuation line over-indented for hanging indent
./act/qc/qctests.py:470:33: E126 continuation line over-indented for hanging indent
./act/qc/qctests.py:557:33: E126 continuation line over-indented for hanging indent
./act/qc/qctests.py:652:33: E126 continuation line over-indented for hanging indent
./act/qc/__init__.py:13:1: W293 blank line contains whitespace
./act/qc/__init__.py:16:25: W291 trailing whitespace
./act/qc/__init__.py:19:1: W391 blank line at end of file
./act/tests/test_qc.py:49:13: E126 continuation line over-indented for hanging indent
./act/tests/test_qc.py:53:13: E126 continuation line over-indented for hanging indent
./act/tests/test_qc.py:59:23: E126 continuation line over-indented for hanging indent
./act/tests/test_qc.py:82:13: E128 continuation line under-indented for visual indent
./act/tests/test_qc.py:83:25: E712 comparison to True should be 'if cond is True:' or 'if cond:'
./act/tests/test_qc.py:87:13: E128 continuation line under-indented for visual indent
./act/tests/test_qc.py:92:13: E128 continuation line under-indented for visual indent
./act/tests/test_qc.py:96:9: E128 continuation line under-indented for visual indent
./act/tests/test_qc.py:98:13: E128 continuation line under-indented for visual indent
./act/tests/test_qc.py:101:68: E203 whitespace before ','
./act/tests/test_qc.py:102:13: E128 continuation line under-indented for visual indent
./act/tests/test_qc.py:102:13: E231 missing whitespace after ','
./act/tests/test_qc.py:104:13: E128 continuation line under-indented for visual indent
./act/tests/test_qc.py:109:13: E128 continuation line under-indented for visual indent
./act/tests/test_qc.py:113:13: E128 continuation line under-indented for visual indent
./act/tests/test_qc.py:115:13: E128 continuation line under-indented for visual indent
./act/tests/test_qc.py:120:13: E128 continuation line under-indented for visual indent
./act/tests/test_qc.py:125:13: E128 continuation line under-indented for visual indent
./act/tests/test_qc.py:129:13: E128 continuation line under-indented for visual indent
./act/tests/test_qc.py:133:1: W391 blank line at end of file

**Pull request merged**
