### PR TITLE
Adding Ability to Query CropScape API to get Crop Type

### PR DESCRIPTION
**Pull request by AdamTheisen**

### CODE REVIEW

**Comment by AdamTheisen** [comment]
Removing Bobby as reviewer and adding Zach.

**Comment by zssherman** [comment]
@AdamTheisen For the code itself, I would maybe move the imports outside of the functions, personal preference I guess, but ultimately up to you.
Documentation wise, I would add for the function the category return in the doc string:
returns
---------
category : etc
    A etc etc
There are also some extra spaces in the docstring paragraph too.
Besides that looks good to me.

**Comment by zssherman** [comment]
Oh and import order for pep8 should be:
import datetime

import pyproj
import requests

datetime is python built in package and pyproj and requests are third party

**Comment by AdamTheisen** [comment]
thanks @zssherman  I made the changes and added a test as well.

**Comment by AdamTheisen** [comment]
@zssherman what do you think?  good to go now?

**Comment by zssherman** [comment]
@AdamTheisen Yeah, I would say its ready to merge.

**Pull request merged**
