### PR TITLE
Trying to get qc documentation to render correctly. 

### PR DESCRIPTION
**Pull request by kenkehoe**
Made some fixes but still not working.

Please hold off on merging.

### CODE REVIEW

**Comment by kenkehoe** [comment]
I'm only doing the pull request so you can see where I'm at. I fixed some issues with document strings but it still does not work. I keep getting an error I don't understand.

Warning, treated as error:
/Users/kehoe/dev/dq/lib/python/ACT/docs/source/API/generated/act.qc.qcfilter.rst:document isn't included in any toctree

Anyone have suggestions?

**Comment by AdamTheisen** [comment]
There's a class defined in qcfilter of QCFilter.

**Comment by kenkehoe** [comment]
I've tried every possible permutation. I don't know.

**Comment by zssherman** [comment]
@kenkehoe For qcfilter, the path is act.qc.filter, when it should be act.qc.qcfilter to match the module path

**Comment by zssherman** [comment]
Nvm see it as part of your changes

**Comment by rcjackson** [comment]
The CI passed, so the docs are not failing to build from a clean build, but only on Ken's machine. 

On your machine, Ken, try demoving every file in the /Users/kehoe/dev/dq/lib/python/ACT/docs/source/API/generated/ directory. This is only generated after the make is done and if there are unused files there it will fail.

**Comment by AdamTheisen** [comment]
I think I have a fix for all this based on Ken's updates.  If you want I can do a pull request.  It would also include the new cloud base height detection algorithm I have.

**Comment by kenkehoe** [comment]
If @AdamTheisen  has a possible solution then I suggest we try that.

**Comment by AdamTheisen** [comment]
@kenkehoe I'll close this pull request and then have you submit new once you update the code from #107

**Pull request closed without merging**
