### PR TITLE
adding precipitable water calculation for sonde data

### PR DESCRIPTION
**Pull request by cgodine**
For some of our DQ Office plots, we have been calculating precipitable water vapor values from sonde data, notably to compare with other instruments that measure pwv directly (see image). This was done in our IDL code as well, but I re-wrote it in python with more up-to-date equations. I think that this would be useful to have in ACT for anyone who is using ARM sonde data.
nsacsphotC1 a1 pwv 232830 20190817

### CODE REVIEW

**Comment by AdamTheisen** [comment]
Looks like some PEP8 errors

./act/retrievals/pwv_calc.py:40:57: E226 missing whitespace around arithmetic operator
./act/retrievals/pwv_calc.py:40:60: E226 missing whitespace around arithmetic operator
./act/retrievals/pwv_calc.py:41:35: E226 missing whitespace around arithmetic operator
./act/retrievals/pwv_calc.py:44:62: E226 missing whitespace around arithmetic operator
./act/retrievals/pwv_calc.py:45:35: E226 missing whitespace around arithmetic operator
./act/retrievals/pwv_calc.py:50:25: E226 missing whitespace around arithmetic operator
./act/retrievals/pwv_calc.py:73:28: E226 missing whitespace around arithmetic operator
./act/retrievals/pwv_calc.py:79:24: E226 missing whitespace around arithmetic operator
./act/retrievals/pwv_calc.py:79:37: E226 missing whitespace around arithmetic operator
./act/retrievals/pwv_calc.py:79:48: E226 missing whitespace around arithmetic operator
./act/retrievals/pwv_calc.py:79:52: E226 missing whitespace around arithmetic operator
./act/retrievals/pwv_calc.py:79:64: E226 missing whitespace around arithmetic operator
./act/retrievals/pwv_calc.py:79:67: E226 missing whitespace around arithmetic operator

**Comment by AdamTheisen** [comment]
@cgodine can you also add a unit test to the act/tests/test_retrievals.py script?  There should already be sonde data under act/tests/data.  You could grab the sgpsonde file for 20190101 and have the test assert what the value should be.

**Comment by cgodine** [comment]
@AdamTheisen for some reason that PEP8 rule isn't showing up when I run flake8. I think I managed to get all of those spaces but if I missed any I'll re-commit.

**Comment by AdamTheisen** [comment]
@cgodine A couple other things

The unit test is failing

    def test_calculate_precipitable_water():
        sonde_ds = act.io.armfiles.read_netcdf(
            act.tests.sample_files.EXAMPLE_SONDE1)
        assert sonde_ds["tdry"].units == "C", "Temperature must be in Celsius"
>       pwv_data = act.retrievals.pwv_calc.calculate_precipitable_water(
            sonde_ds, temp_name='tdry', rh_name='rh', pres_name='pres')
E       AttributeError: module 'act.retrievals' has no attribute 'pwv_calc'

Are you adding pwv_calc to the __init__.py file in act/retrievals?

**Comment by cgodine** [comment]
Sorry about that @AdamTheisen! Must have forgotten.

**Comment by AdamTheisen** [comment]
One last pep8 

./act/tests/test_retrievals.py:37:1: E302 expected 2 blank lines, found 1

**Comment by AdamTheisen** [comment]
Method looks sound and compares well with the other instrument from the example.  Will merge...

**Pull request merged**
