### PR TITLE
Geoplot2

### PR DESCRIPTION
**Pull request by kenkehoe**
I was having an issue with the test running and test for plot_from_u_and_v(). I also made a few minor changes to the new plotting stuff I did. This is not fixing my py.test issue but I do need the plot_from_u_and_v() to let the test pass.

### CODE REVIEW

**Comment by AdamTheisen** [comment]
Requesting Bobby as a reviewer.

I never had issues with the plot_from_u_and_v test so I am a little concerned about potential conflicts on the ADC system.

**Comment by rcjackson** [comment]
I wonder if there is some sort of setting in the ADC environment that is making it fail. I'll try the test on my own end and see what I get.

**Comment by rcjackson** [comment]
For your py.test issue I tried simply running the test manually and I get this figure.
myfig

Therefore, I think there might be an issue with pytest-mpl when it preserves the figure colormap. I'll look into raising an issue on their webpage.

**Comment by rcjackson** [comment]
I have raised this as an issue. We can see if it's truly a problem on their end or something we need to do.

https://github.com/matplotlib/pytest-mpl/issues/84

**Comment by kenkehoe** [comment]
OK thanks. Can we comment out the test with our stuff for now?

**Comment by rcjackson** [comment]
Yeah let's not do the test for now.

Bobby
________________________________

**Pull request merged**
