### PR TITLE
Sobel Cloud Base Height Calculation

### PR DESCRIPTION
**Pull request by AdamTheisen**
Using edge detection to determine cloud base height from lidars/vertically pointing radars.  Tested on KAZR/MPL

### CODE REVIEW

**Comment by rcjackson** [comment]
Tests are passing and documentation looks good. I am for merging this in.

**Comment by AdamTheisen** [comment]
@rcjackson @zssherman I probably need to add a test for this, but will probably test out on the existing ceil data so we don't need to add a larger mpl/kazr file to the repo

**Comment by rcjackson** [comment]
Good point @AdamTheisen, I forgot about that, but this does need a unit test.

________________________________

**Comment by AdamTheisen** [comment]
Closing out without merge... accidentally included in another pull request.

**Pull request closed without merging**
